import 'package:flutter/widgets.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

/// Maps deck icon names (from levels.json) to Phosphor icons.
///
/// Keys are the kebab-case names stored in the "icon" field of each deck.
/// Returns [PhosphorIconsRegular.cards] as fallback for unknown names.
class DeckIcons {
  static const IconData fallback = PhosphorIconsRegular.cards;

  static IconData fromString(String name) => _map[name] ?? fallback;

  static const _map = <String, IconData>{
    'hand-wave': PhosphorIconsRegular.handWaving,
    'compass-outline': PhosphorIconsRegular.compass,
    'heart-pulse': PhosphorIconsRegular.heartbeat,
    'lightbulb-outline': PhosphorIconsRegular.lightbulb,
    'alphabetical-variant': PhosphorIconsRegular.textAa,
    'silverware-fork-knife': PhosphorIconsRegular.forkKnife,
    'human': PhosphorIconsRegular.person,
    'account-group': PhosphorIconsRegular.usersThree,
    'bread-slice': PhosphorIconsRegular.bread,
    'home-outline': PhosphorIconsRegular.house,
    'numeric': PhosphorIconsRegular.hash,
    'road-variant': PhosphorIconsRegular.roadHorizon,
    'thumbs-up-down': PhosphorIconsRegular.thumbsUp,
    'link-variant': PhosphorIconsRegular.link,
    'run': PhosphorIconsRegular.personSimpleRun,
    'hand-back-right': PhosphorIconsRegular.hand,
    'emoticon-happy-outline': PhosphorIconsRegular.smiley,
    'human-handsup': PhosphorIconsRegular.personArmsSpread,
    'human-male-female-child': PhosphorIconsRegular.usersThree,
    'basket': PhosphorIconsRegular.basket,
    'floor-plan': PhosphorIconsRegular.house,
    'palette': PhosphorIconsRegular.palette,
    'calendar-month': PhosphorIconsRegular.calendar,
    'clock-outline': PhosphorIconsRegular.clock,
    'paw': PhosphorIconsRegular.pawPrint,
    'city': PhosphorIconsRegular.buildings,
    'scale-balance': PhosphorIconsRegular.scales,
    'earth': PhosphorIconsRegular.globe,
    'bag-suitcase': PhosphorIconsRegular.suitcase,
    'head-heart': PhosphorIconsRegular.brain,
    'swap-horizontal': PhosphorIconsRegular.arrowsLeftRight,
    'hammer-wrench': PhosphorIconsRegular.wrench,
    'puzzle': PhosphorIconsRegular.puzzlePiece,
    'face-man-shimmer': PhosphorIconsRegular.smileyWink,
    'sofa': PhosphorIconsRegular.couch,
    'food-variant': PhosphorIconsRegular.cookingPot,
    'pine-tree': PhosphorIconsRegular.treeEvergreen,
    'hand-pointing-up': PhosphorIconsRegular.handPointing,
    'map-marker-account': PhosphorIconsRegular.mapPin,
    'briefcase-outline': PhosphorIconsRegular.briefcase,
    'map-clock': PhosphorIconsRegular.mapTrifold,
    'airplane': PhosphorIconsRegular.airplane,
    'heart-outline': PhosphorIconsRegular.heart,
    'pill': PhosphorIconsRegular.pill,
    'stairs-up': PhosphorIconsRegular.stairs,
    'rocket-launch': PhosphorIconsRegular.rocketLaunch,
    'vector-curve': PhosphorIconsRegular.bezierCurve,
    'format-list-group': PhosphorIconsRegular.listBullets,
    'bone': PhosphorIconsRegular.bone,
    'star-outline': PhosphorIconsRegular.star,
    'palette-swatch': PhosphorIconsRegular.swatches,
    'book-open-variant': PhosphorIconsRegular.bookOpen,
    'peace': PhosphorIconsRegular.peace,
    'code-braces': PhosphorIconsRegular.code,
    'cash-multiple': PhosphorIconsRegular.money,
    'moon-waning-crescent': PhosphorIconsRegular.moon,
    'elephant': PhosphorIconsRegular.dog,
    'stethoscope': PhosphorIconsRegular.stethoscope,
    'dolphin': PhosphorIconsRegular.fish,
    'pot-steam': PhosphorIconsRegular.cookingPot,
    'brush': PhosphorIconsRegular.paintBrush,
    'domain': PhosphorIconsRegular.buildings,
    'gavel': PhosphorIconsRegular.gavel,
    'laptop': PhosphorIconsRegular.laptop,
    'atom': PhosphorIconsRegular.atom,
    'table-furniture': PhosphorIconsRegular.table,
    'infinity': PhosphorIconsRegular.infinity,
    'trophy': PhosphorIconsRegular.trophy,
    'toothbrush': PhosphorIconsRegular.tooth,
    'movie-open': PhosphorIconsRegular.filmSlate,
    'school': PhosphorIconsRegular.graduationCap,
    'terrain': PhosphorIconsRegular.mountains,
    'car': PhosphorIconsRegular.car,
    'toolbox': PhosphorIconsRegular.toolbox,
    'ring': PhosphorIconsRegular.diamond,
    'fire': PhosphorIconsRegular.fire,
  };
}
